# Generated by Django 4.2.8 on 2025-05-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('cover', models.URLField()),
                ('author', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('adult', models.BooleanField()),
                ('category_id', models.IntegerField()),
                ('price_standard', models.IntegerField()),
                ('link', models.URLField()),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
