# Generated by Django 4.2.21 on 2025-05-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image_object', models.URLField()),
                ('author', models.CharField(blank=True, default='미상', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('view_count', models.IntegerField()),
            ],
        ),
    ]
