# Generated by Django 4.2.21 on 2025-05-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='image_object',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='link',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category_id',
            new_name='view_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price_standard',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default='미상', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
