# Generated by Django 4.2.21 on 2025-05-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default='미상', max_length=20, null=True),
        ),
    ]
