# Generated by Django 4.2.21 on 2025-05-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookreport_bookreportcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reports', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookreportcomment',
            name='book_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='books.bookreport'),
        ),
    ]
