# Generated by Django 4.2.21 on 2025-05-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_mbtirecommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreport',
            name='image',
        ),
    ]
