# Generated by Django 4.2.21 on 2025-05-27 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_remove_bookreport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='recommend_users',
            field=models.ManyToManyField(blank=True, related_name='recommend_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
