# Generated by Django 4.2.21 on 2025-05-25 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreport',
            name='recommend_users',
            field=models.ManyToManyField(blank=True, related_name='recommend_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
