# Generated by Django 4.2.21 on 2025-05-25 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_reports', '0002_bookreport_recommend_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreport',
            name='recommend_users',
        ),
        migrations.AddField(
            model_name='bookreport',
            name='like_report_users',
            field=models.ManyToManyField(blank=True, related_name='like_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
