# Generated by Django 4.2.21 on 2025-05-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreportcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
