# Generated by Django 4.2.21 on 2025-05-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatmessage_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='messeage',
            new_name='message',
        ),
    ]
